# Use an official Python runtime as a parent image
FROM python:3.12-slim

LABEL maintainer="mjunaidca"
# Set the working directory in the container
WORKDIR /code
ENV PYTHONPATH=/code

# Copy the Poetry lock file and pyproject.toml file to the container
COPY pyproject.toml poetry.lock* ./

# Install Poetry
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Copy the current directory contents into the container at /code
COPY . /code/

# Make port 8000 available to the world outside this container
EXPOSE 8000

CMD ["/bin/bash","-c", "uvicorn poetry_project.main:app --reload --host 0.0.0.0 --port 8000"]